### ISSUE TITLE
A real project to exercises

### ISSUE THREAD

**Issue by ggangliu** [RobertBaruch/amaranth-exercises#1]
Hi Robert,
Really thanks for your this execises. If is it possible to start a real project to practice amaranth, for example, start to write a risc-v CPU. Or already have it in somewhere?

**Comment by XekriRedmane** [comment]
You can see my video series on building a 6800 CPU using nMigen. Converting to Amaranth is trivial.

https://www.youtube.com/watch?v=85ZCTuekjGA
